In [12]:
import pandas as pd
import os
import zipfile

In [2]:
data = pd.read_csv("data/metadonnees.csv")
data.head()

C:\Users\auran\AppData\Local\Temp\ipykernel_10916\3855839679.py:1: DtypeWarning: Columns (8,9,10,12,28,29,30,31,32,33,34,35,36,37,38,39,40,41) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("data/metadonnees.csv")

,id,date,subject,title,contexte-election,contexte-tour,cote,departement,departement-nom,departement-insee,...,suppleant-age-calcule,suppleant-age-tranche,suppleant-profession,suppleant-mandat-en-cours,suppleant-mandat-passe,suppleant-associations,suppleant-autres-statuts,suppleant-soutien,suppleant-liste,suppleant-decorations
0,EL009_L_1958_11_001_01_1_PF_01,1958-11-23,France;Élections législatives;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,maire;conseiller général,non mentionné,non mentionné,non mentionné,Parti radical,non mentionné,non
1,EL009_L_1958_11_001_01_1_PF_02,1958-11-23,France;Ve République;Élections législatives;As...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,conseiller municipal,non mentionné,non mentionné,prisonnier de guerre,Union pour la nouvelle République,non mentionné,non
2,EL009_L_1958_11_001_01_1_PF_03,1958-11-23,Élections législatives;France;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur,non mentionné,non mentionné,non mentionné,non mentionné,Parti communiste français,non mentionné,non
3,EL009_L_1958_11_001_01_1_PF_04,1958-11-23,Élections législatives;France;Assemblée Nation...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,35,entre 30 et 39 ans,greffier de paix,conseiller municipal;conseiller général,non mentionné,non mentionné,combattant,non mentionné,non mentionné,oui
4,EL009_L_1958_11_001_01_1_PF_05,1958-11-23,Ve République;Assemblée Nationale;Élections lé...,"Élections législatives de 1958, Ain - 01, circ...",législatives,1,EL009,01,Ain,01 - Ain,...,non mentionné,non mentionné,cultivateur;président Coopérative élevage,non mentionné,non mentionné,non mentionné,non mentionné,Centre national des indépendants et paysans,non mentionné,non

In [9]:
data.columns

Index(['id', 'date', 'subject', 'title', 'contexte-election', 'contexte-tour',
       'cote', 'departement', 'departement-nom', 'departement-insee',
       'identifiant de circonscription', 'images', 'pdf', 'ocr_url',
       'titulaire-nom', 'titulaire-prenom', 'titulaire-sexe', 'titulaire-age',
       'titulaire-age-calcule', 'titulaire-age-tranche',
       'titulaire-profession', 'titulaire-mandat-en-cours',
       'titulaire-mandat-passe', 'titulaire-associations',
       'titulaire-autres-statuts', 'titulaire-soutien', 'titulaire-liste',
       'titulaire-decorations', 'suppleant-nom', 'suppleant-prenom',
       'suppleant-sexe', 'suppleant-age', 'suppleant-age-calcule',
       'suppleant-age-tranche', 'suppleant-profession',
       'suppleant-mandat-en-cours', 'suppleant-mandat-passe',
       'suppleant-associations', 'suppleant-autres-statuts',
       'suppleant-soutien', 'suppleant-liste', 'suppleant-decorations'],
      dtype='object')

In [9]:
data["date"] = pd.to_datetime(data["date"])

data[["annee","mois","jour"]] = data["date"].apply(
    lambda x: pd.Series([x.year, x.month, x.day])
)
print("Nombre de professions par années :", data["annee"].value_counts().sort_index())

Nombre de professions par années : annee
1958    2774
1959       7
1962    2235
1965       8
1967    2871
1968    2872
1969       8
1973    3843
1974      13
1978    4830
1979       7
1981    3133
1986     740
1988    3551
1989      13
1993    5837
1995      11
1999      14
2002      18
2004      50
2007      13
2009      60
2012      12
2014      97
2019      13
Name: count, dtype: int64

In [13]:
# Export des professions de foi
zip_path = "C:/Users/auran/OneDrive/Documents/ensae/3A/NLP/legislatives.zip"

docs = []

with zipfile.ZipFile(zip_path) as z:
    for file in z.namelist():
        if file.endswith(".txt"):
            with z.open(file) as f:
                text = f.read().decode("utf-8", errors="ignore")
                docs.append({"file": file, "text": text})

transcriptions = pd.DataFrame(docs)

In [ ]:
transcriptions["id"] = transcriptions["file"].str.extract(r'([^/]+)\.txt')

In [19]:
transcriptions.head()

                                                              file  \
0  text_files/1993/legislatives/EL196_L_1993_03_076_12_1_PF_01.txt
1  text_files/1993/legislatives/EL190_L_1993_03_024_02_1_PF_03.txt
2  text_files/1993/legislatives/EL190_L_1993_03_017_01_1_PF_07.txt
3  text_files/1993/legislatives/EL192_L_1993_03_050_02_1_PF_03.txt
4  text_files/1993/legislatives/EL196_L_1993_03_079_04_1_PF_03.txt

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  text  \
0  Département de Seine-Maritime - 12ème Circonscription - Scrutin du 21 Mars 1993\nAlain LE VERN Député Maire de Saint-Saëns - 44 ans Suppléant : Docteur Christian PLAILLY Maire de GAILLEFONTAINE - 44 ans\nChère Madame, Chère Mademoiselle, Cher Monsieur,\nVoici 5 ans vous m'avez élu Député. J'ai depuis consacré tout mon temps et toute mon énergie pour être digne de votre confiance. La période électorale est trop souvent celle des divisions, des belles promesses ... Jugez les actes, les faits ! Nous n'avons pas tout réussi, bien sûr, mais j'ai travaillé pour rassembler et unir dans l'intérêt de notre circonscription, de ses habitants, de notre Pays.\nDANS NOTRE CIRCONSCRIPTION, J'AI AGI POUR: ☒ La construction de logements (Gournay, La Feuillie, Buchy, Saint-Saëns, Neuville Ferrières, Neufchâtel, Londinières, Blangy, Torcy le Grand, Bellencombre ... une centaine par an au lieu d'une dizaine par an avant !). ☒ Le désenclavement routier : RN 27 Rouen Dieppe, Autoroute A 28 ouverte en décembre dernier jusqu'à Neufchâtel, RN 31 aménagée ... ☒ Une formation de meilleure qualité : adaptation des formations de bacs professionnels en liaison avec les entreprises, ouvertures de BTS, de maternelles. ☒ Le maintien des lignes SNCF grâce à notre action (Elus, usagers, syndicats). Blangy, Aumale, (Paris Le Tréport) Ferrières - Gournay - Forges - Serqueux (Paris-Gisors-Serqueux) conserveront leur gare nécessaire au développement (alors qu'en 1988 on avait hélas fermé Serqueux- Dieppe). ☒ Le soutien efficace à de nombreuses communes et associations pour des réalisations locales. ☒ La défense de notre agriculture en obtenant des mesures spécifiques et adaptées, en aidant la valorisation des produits locaux, en votant "NON" au G.A.T.T. imposé par les U.S.A. ☒ L'aide aux personnes âgées (structures de maintien à domicile), la rénovation de nos maisons de retraite, l'augmentation du nombre de places en cure médicale. ☒ Le développement économique, le commerce et l'artisanat (rénovation de nombreux magasins, accès aux marchés publics pour les petites entreprises ... ), donc pour l'emploi (taux de chômage encore trop élevé mais le plus bas de la région). ☒ Le maintien et l'adaptation des services publics et de santé (services d'urgence de Neufchâtel et Gournay), rénovation de bureaux de poste ... ☒ Le développement du tourisme vert par des réalisations concrètes sur les pôles touristiques (Londinières, Forges, Gournay, Neufchâtel ... ).\nVOILA UNE PARTIE DE MON BILAN\nSciences Po / fonds CEVIPOFCONTINUONS ENSEMBLE\nJe vous propose :\n* de poursuivre l'effort pour l'amélioration du réseau routier (autoroute A 28 Neufchâtel-Blangy en cours, A 29 (vers Aumale-Amiens, RN 31 en 2 fois 2 voies, RN 27, liaisons avec les autoroutes);\n« d'améliorer toujours la formation de notre jeunesse, clé pour l'emploi;\n« de continuer l'action pour le logement (Serqueux, Sommery, Croisy, Mesnières, Gournay, Blangy, Londinières, Gaillefontaine, Neuville Ferrières, Neufchâtel, Aumale, Bellencombre, Les Grandes Ventes, Fourcarmont, St Saëns soit plus de 140 logements sociaux seront construits en 1993);\n· de développer le tourisme vert qui est un atout important;\n* de lutter pour l'emploi et l'implantation d'activités, de développer le commerce et l'artisanat, les petites et moyennes entreprises, essentielles pour nous;\n« de valoriser nos filières d'excellence, pour créer des emplois : industries agro-alimentaires, bois, viande, automobile, industrie du verre, textile, moulage, caoutchouc ...\n· d'aider notre agriculture à s'adapter;\n« de créer les structures utiles à nos personnes âgées;\n· de défendre notre environnement;\n« de moderniser les services publics; ☒ par le soutien à de nombreuses réalisations de nos communes;\nSciences Po / fonds CEVIPOF\n« DE CONTINUER DE TRAVAILLER AU RASSEMBLEMENT DE TOUS, POUR LE BIEN DE TOUS, POUR LE DEVELOPPEMENT ET LA PROMOTION DE NOTRE MONDE RURAL.\nJe défendrai toujours nos valeurs : liberté, justice sociale, égalité des chances, droits des salariés, efficacité économique, défense du droit à la retraite et de la sécurité sociale, honnêteté et transparence.\nVoilà mes engagements. En 1988 je vous avais écrit : «VOUS POUVEZ COMPTER SUR MOI». C'était vrai. J'AI TENU PAROLE, vous le savez. Je vous dis : vous pouvez TOUJOURS compter sur moi.\nJ'ai beaucoup travaillé pour mieux vous représenter. Il y a encore tant à faire ENSEMBLE !\nJ'ai besoin de votre confiance, de votre solution pour-continuer mon travail au service de tous. Je compte sur vous. Chaleureusement. Alain Le Vern\nJ'AI TENU LES ENGAGEMENTS PRIS DEVANT VOUS. ☒ par ma présence (dans pratiquement les 198 communes que je représente), autant d'occasions de dialogues, contacts, prises en compte des réalités locales; ☒ par des permanences décentralisées dans les 1 1 cantons; ☒ par l'ouverture d'un secrétariat permanent (40 000 lettres individuelles, 5000 personnes reçues); ☒ par mon travail parlementaire en faveur de l'emploi, de l'éducation, de notre agriculture, des retraités et personnes âgées, du développement rural, des transports, du logement, de la santé, du sport, des anciens combattants, des sapeurs pompiers, des communes rurales, du tourisme. ☒ par plus de 200 questions écrites aux Ministres; ☒ par ma présence à tous les votes publics à l'Assemblée; ☒ par le soutien à plus de 100 dossiers auprès du médiateur de la République;\nDIMANCHE, VOTEZ ALAIN LE VERN\nVu le Candidat,\nSUPPLEANT : Docteur Christian PLAILLY Maire de GAILLEFONTAINE Alliance des Français pour le progrès\nImp. FERE - Maromme
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ELECTIONS LEGISLATIVES DU 21 MARS 1993\nREPUBLIQUE FRANÇAISE - 2™e CIRCONSCRIPTION DE LA DORDOGNE\nMichel SUCHOD Député du Bergeracois\nSuppléant\nFrançois LASTERNAS Conseiller général de La Force Maire de Prigonrieux\nDEUX SOCIALISTES POUR LA RELEVE DE LA GAUCHE DEUX HOMMES EFFICACES POUR LE BERGERACOIS\nMadame, Mademoiselle, Monsieur,\nComme vous je suis citoyen.\nEt si comme vous, je pense que le gouvernement sortant ne rend pas copie blanche, je pense comme vous qu'il n'a pas su régler le dramatique problème de l'emploi, et qu'il a laissé se développer des « affaires » trop nombreuses et particulièrement nauséabondes.\nIl faut donc changer la politique, pour recréer l'emploi, raffermir la démocratie, sauver la paix.\nCela implique-t-il de liquider le député sortant du Bergeracois pour le remplacer par la représen- tante de la droite conservatrice comme certains le souhaitent ? Poser la question, c'est y répondre par la négative.\nBien mieux, il faut garder Michel SUCHOD, le député qui :\n- EST A L'ECOUTE DE TOUS, qui tient dans chaque canton et à Bergerac des permanen- ces décentralisées, et que chacun de vous peut facilement rencontrer pour solliciter son aide (3.000 dossiers individuels traités dans la législature); pourquoi le remplacer par une dame déjà titulaire de plusieurs mandats et qui n'est pas en mesure de ce seul fait de faire comme lui ?\n- QUI A EU LE COURAGE DE MANIFESTER SON INDEPENDANCE d'esprit, en votre nom, au Parlement, en refusant la discipline de fer des partis, et en se prononçant par exemple, avec fermeté, contre l'amnistie, malgré l'opinion de son groupe; a-t-on besoin d'une dame député qui sera un député-godillot de plus dans un vaste groupe conservateur ? Est-il bon que la voix du Bergeracois cesse d'être entendue au Parlement ?\n- QUI DEFEND UN PROGRAMME NOVATEUR, pour l'emploi, la démocratie, la paix, l'environnement et la jeunesse, et non le retour au conservatisme le plus limité, sur l'école, la famille, le service public, les bas salaires, comme sa challenger de droite le propose dans son programme national, que du reste, elle a la prudence de ne pas présenter sur le terrain.\nOUI, GARDONS NOTRE DEPUTE, ET POUR CELA VOTONS POUR LUI DES LE PREMIER TOUR\nSciences Po / fonds CEVIPOF ☐ ☐La priorité des priorités : L'EMPLOI\n« Notre premier devoir est de créer des emplois pour assurer l'insertion de la jeunesse et retrouver du travail à tous ceux qui en sont écartés ».\nPour faire reculer le chômage qui est au cœur de toutes nos difficultés, je propose de : 1. Faire baisser d'au moins trois points le niveau des taux d'intérêts réels qui asphyxient notre économie (8 % en France, contre 0 % aux Etats-unis et 2,5 % au Japon).\n2. Changer la donne européenne (réforme du SME, initiative européenne de crois- sance, préférence européenne).\n3. Définir des politiques industrielles, européennes ou, à défaut, nationales, comme par exemple pour notre poudrerie.\n4. Mettre un terme à la crise de la construction et du logement social, aider le bâtiment et l'artisanat.\n5. Accroître le travail pour le mieux partager.\n6. Préserver notre agriculture et nos paysans au GATT, contre les pressions américai- nes, et à Bruxelles.\nPar une croissance mieux maîtrisée, nous pourrons ainsi : Maintenir notre protection sociale (retraite à soixante ans et principe de la répartition); Financer la défense de l'environnement, car le capital naturel n'est pas illimité.\nSciences Po / fonds CEVIPOF\nL'APPEL DE FRANÇOIS LASTERNAS Candidat suppléant\n« Si j'ai rejoins Michel SUCHOD, si je me bats à ses côtés dans cette élection, c'est que, dans cette période très difficile que traverse le pays, j'ai voulu contribuer par mon appui à SAUVER UN SIEGE DE DEPUTE DE GAUCHE, DE DEPUTE SOCIALISTE pour la Dordogne.\nOui, il serait catastrophique que notre département, gouverné depuis l'an dernier à Périgueux par la droite, qui est déjà dans une Région dirigée depuis Bordeaux, par la droite, soit représenté par 4 députés de droite au Parlement ».\nSauver le siège de Bergerac est possible, si vous votez utile dès le premier tour.\nToute la gauche doit se mobiliser dès maintenant afin d'assurer le sursaut du deuxième tour, qui permettra de l'emporter.\nLe siège de Bergerac dépend de chacune, de chacun d'entre vous.\nOFFSET JOUCLA - BOULAZAC\nVU, LES CANDIDATS.

In [17]:
pd.set_option('display.max_colwidth', None)
# YOUR CODE HERE
transcriptions.sample()

                                                                file  \
532  text_files/1993/legislatives/EL196_L_1993_03_078_06_1_PF_03.txt

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text
532  ensemble\n6 ème Circonscription 21 Mars Elections législatives\nContre la droite\nPierre Soulat\nMaire d'Achères\nCandidat d'union et de rassemblement Soutenu par le P. C. F. Suppléant : Alain Binet ( Professeur agrégé à s' Germain )\n' Une vraie politique de gauche Il\nSciences Po / fonds CEVIPOF21 Mars\nEnsemble pour construire et répondre enfin à vos attentes.\nE n 1981 , nous espérions la mise en œuvre d'une politique de Gauche pour changer la vie, faire régner la justice, l'égalité, la citoyenneté, créer les conditions du progrès social et de l'épanouissement de chacun. Nous rêvions d'entente, de Paix, du recul de la faim, de la maladie dans le monde. Impatients de mettre notre enthousiasme au service de l'Homme et non des profits, nous voulions préparer à notre jeunesse un avenir de tolérance, d'amitié, de goût de l'effort.\nMalheureusement les gouvernements socialistes n'ont pas respecté leurs engagements et ont appliqué une politique de droite\nLe chômage n'épargne aucune famille .Précarité, exclusion, insécurité rongent la société et s'accompagnent de menaces sur les droits au logement, sécurité sociale et retraites, l'école et la formation. Les inégalités se sont creusées. La jeunesse se désespère de ne pouvoir mettre son enthousiasme au service de la collectivité. Les questions d'environnement nous préoccupent à juste titre .\nIl La déception est grande.\nUn désarroi a remplacé l'enthousiasme, dans un monde bouleversé et lourd d'inquiétudes nouvelles. Il faut donc trouver des moyens et des solutions répondant aux besoins et ne plus pratiquer une politique favorisant le retour de la droite qui, aujourd'hui, s'apprête à pratiquer une politique plus dure et plus inégalitaire que jamais. Ses intentions font planer le danger d'une aggravation dans tous les domaines. Faites-y barrage en votant pour ceux qui vous défendent le mieux, ceux qui rassemblent pour une vraie politique de Gauche.\nSi je respecte l'idée de ceux qui pensent que le vote "écologique" pourrait être utile et préparer du neuf, je suis cependant inquiet et déçu des responsables de partis écologistes qui, dans la course aux postes ministériels, envisagent des alliances avec RPR et UDFdont ils se disent souvent en accord sur les solutions à mettre en œuvre.\nOr depuis 16 ams que je suis maire d'Achères l'environnement est au centre de mon action, en l'intégrant à la nécessité de répondre aux besoins de la population. Constamment sur le terrain pour la défense de la forêt, d'une Seine propre aux berges accueillantes, d'une amélioration du traitement des eaux usées, la disparition de l'épandage, une solution satisfaisante pour le traitement des déchets ménagers, je me bats aussi pour le développement des transports en\ncommun, l'ouverture aux voyageurs de la Grande Ceinture jusqu'à Versailles/St Quentin et prolongement vers Cergy via Achères, l'implantation d'un IUT et d'un centre de recherche et de formation aux métiers de l'environnement, la mise en place d'un réseau routier sans péage respectant la qualité et le cadre de vie des habitants.\nDans notre circonscription taillée sur mesure pour la droite, il faut une force d'opposition unie, résolue. Evitons la dispersion des suffrages. Achères y est la seule ville gérée par une liste d'Union de la Gauche (communistes, socialistes, écologistes, démocrates) liste que j'ai l'honneur d'animer depuis 1977 comme maire communiste. Face au candidat unique de la liste de droite et à la candidate du parti raciste (Front National), je suis le mieux placé pour regrouper ceux qui veulent une société de justice et d'égalité plaçant l'Homme au centre d'une politique basée sur les valeurs de Gauche retrouvées.\n# Construisons ensemble cette société humaine, pluraliste, respectueuse de tous. Préparons l'avenir à nos enfants et nos jeunes. Il est temps d'arrêter la démagogie et la politique politicienne mais d'apporter enfin des réponses à nos problèmes quotidiens. Rassemblons-nous pour une vraie politique de Gauche.\nJ'appelle donc les électeurs écologistes, socialistes, communistes, ceux qui ont le coeur à gauche ou qui s'abstiendraient par perte de confiance, à se retrouver dans la démarche unitaire que je leur propose. Je vous appelle à réfléchir et débattre, à redonner un sens à votre citoyenneté, à contester la domination de l'argent et du capitalisme. J'appelle les jeunes à prendre leur place dans ce combat pour un avenir de justice, de solidarité et de luttes pour les grandes causes humaines. Il faut un monde à l'endroit, fait pour l'Etre Humain.\nDans ce sens, je vous assure de mon entier dévouement. J'y mettrai autant de coeur et de passion que dans mon action pour faire d'Achères une ville dynamique et solidaire. Vous pouvez aussi compter sur mon ami Alain Binet, suppléant.\nPierre SOULAT\nVotez Pierre SOULAT\nCandidat d'Union et de Rassemblement pour une vraie politique de Gauche. Soutenu par le Parti Communiste Français.\nSEY 30.55.00.13\nVu / Le candidat\nSciences Po / fonds CEVIPOF